### ISSUE TITLE
I need you help

### ISSUE THREAD

**Issue by EequalmcUP2** [bilogic/esp32-ble#1]
Hello 
I'm create project for keep data from blood pressure monitor(omron hem 7361t) but i' can't get data from BLE.
![Uploading IMG20210712002940.jpg…]()

**Comment by EequalmcUP2** [comment]
![IMG20210712002940](https://user-images.githubusercontent.com/83306885/125207811-c14f6d80-e2b8-11eb-96cc-ecfb85cbdee6.jpg)

**Comment by bilogic** [comment]
Hi, did the callbacks happen?

**Comment by EequalmcUP2** [comment]
My phoe can get data from hem 7361t BLE but esp32 can't get it.
![Screenshot_2021-07-12-00-29-29-31_3c2e989be58abe9ca7463ffb1e6967d2](https://user-images.githubusercontent.com/83306885/125284143-4aab8200-e343-11eb-92da-6e40ee63f381.jpg)

**Comment by bilogic** [comment]
Anything appears after `Success! Waiting for callbacks`?

**Comment by EequalmcUP2** [comment]
Nothing happens, and now I'm read hem 7361t manual about BLE.

**Comment by bilogic** [comment]
1. In your OP's screenshot, the lines that start with [E] are errors. 
2. I can tell things started to go wrong here https://github.com/bilogic/esp32-ble/blob/5cf69e1a1a0c2c612a1453dcd4e8cb03cf2c7831/src/main.cpp#L165
3. Did you change any parts of the code from this repo?

**Comment by bilogic** [comment]
Try and use markdown instead of screenshots, it's easier to read and look for errors.

**Comment by EequalmcUP2** [comment]
I hope you help me for next time, Thank you.

**Comment by bilogic** [comment]
Problem solved?

**Comment by EequalmcUP2** [comment]
If I change hem 7361t to bc85, Can i use you code?

**Comment by bilogic** [comment]
I use the BC85, it worked for me.
I can't guarantee it will work with your BC85, but I'm happy to try and help you.

**Comment by EequalmcUP2** [comment]
I'm very sorry, I can't purchase BC 85 in Thailand but i have bm57.
